file-save-imgPath: G:/video_web/img/
file-save-Portrait: G:/video_web/Portrait/
file-save-videoPath: G:/video_web/video/
file-save-AnimePath: G:/video_web/anime/
file-save-SlideShow: G:/video_web/SlideShow/
file-save-AnimeCoverPath: G:/video_web/anime_cover/
file-save-TvPath: G:/video_web/tv/
file-save-TvCoverPath: G:/video_web/tv_cover/
